services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scraper-app
    restart: unless-stopped
    environment:
      - SERVER_PORT=8080
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=scraper
      - DB_SSLMODE=disable
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - scraper-network

  postgres:
    image: postgres
    container_name: scraper-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=scraper
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - scraper-network

volumes:
  postgres_data:

networks:
  scraper-network:
    driver: bridge